blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/jhpce-jhu/jhpce_mkdocs/discussions
    about: Please ask and answer questions here.
  - name: Mew User Form
    url: https://github.com/jhpce-jhu/jhpce_mkdocs/issues
    about: Please complete this form to request a new account on the JHPCE cluster.
